theme: jekyll-theme-modernist
title: Makayla Campbell
description: Who Am I?
show_downloads: true
github:
  zip_url: https://github.com/SquirrelGrl/SquirrelGrl.github.io/raw/master/MakaylaCampbellProjectsPortfolioV3.pdf
