theme: jekyll-theme-modernist
title: Makayla Campbell
description: Putting the "fun" in functional
show_downloads: true
github:
  zip_url: https://github.com/SquirrelGrl/SquirrelGrl.github.io/raw/master/MakaylaCampbellProjectsPortfolioV3.pdf
